# Generated by Django 5.1 on 2024-08-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
