# Generated by Django 5.1 on 2024-10-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleJSONRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
